name: Deploy to Firebase Preview Channels form Jira

on:
  workflow_dispatch:

jobs:
  preview-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 5. Desplegar a un canal de vista previa
      - name: Deploy to Firebase Preview Channel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          BRANCH_NAME=${{ github.ref_name }}
          firebase hosting:channel:deploy $BRANCH_NAME
